### ISSUE TITLE
Drop-down for user to select their region

### ISSUE THREAD

**Issue by ignatiusm** [dragonfly-science/fish-ibi-calculator#57]
Drop down on first page where Users can select _one_ option from a list of regional councils including a 'No Region' option which is selected by default.

This selection affects the results page (need to keep state for later).

STAG report (with region-specific thresholds) only has 15 regions, using codes from REC. I'll post region names below.

Initial job for @yvanrichard , followed by polishing by @mike-parkin . @ignatiusm to provide region names.

**Comment by yvanrichard** [comment]
The Stat.NZ shapefile of regions has 16 regions (excluding the Chathams). What's different?
 1 Northland          
 2 Auckland           
 3 Waikato            
 4 Bay of Plenty      
 5 Gisborne           
 6 Hawke's Bay        
 7 Taranaki           
 8 Manawatū-Whanganui 
 9 Wellington         
10 West Coast         
11 Canterbury         
12 Otago              
13 Southland          
14 Tasman             
15 Nelson             
16 Marlborough

**Comment by ignatiusm** [comment]
Adam's document (attached references REC region boundaries). I've asked for explanation.

[Fish IBI report MfE style V3.docx](https://github.com/dragonfly-science/fish-ibi-calculator/files/10072036/Fish.IBI.report.MfE.style.V3.docx)

**Comment by ignatiusm** [comment]
Here is a file with interim (bogus) data for regional IBI scores (to be updated with actual numbers from Adam):

[regional_ibi_categories.csv](https://github.com/dragonfly-science/fish-ibi-calculator/files/10072038/regional_ibi_categories.csv)

**Comment by yvanrichard** [comment]
Done. Style to be polished by @mike-parkin
