### ISSUE TITLE
Fish species lookup table

### ISSUE THREAD

**Issue by ignatiusm** [dragonfly-science/fish-ibi-calculator#62]
There are some species codes that are in common use that are not found in 2004 IBI report. This is partially due to changes in taxonomy.

The solution here is to use a lookup table so that contemporary species codes can be used in the app, but are mapped to equivalent species (and species metrics) in 2004 report.

Here is a (bogus) lookup table. Actual data to be provided by MFE.

[fish_code_lookup.csv](https://github.com/dragonfly-science/fish-ibi-calculator/files/10072045/fish_code_lookup.csv)

**Comment by ignatiusm** [comment]
There will be cases where a 2004 species code is still commonly used, and others where a 2004 code is no longer used. In the latter case, I'm not sure what to do if a user uploads a record with 2004 code and another with the contemporary code (this will artificially inflate the species richness). Maybe we need a warning @yvanrichard ?

**Comment by yvanrichard** [comment]
Done.
The species codes are now standardised using the lookup table.
A mix of old and contemporary codes for the same species leads to the same species code, therefore the species richness does not get inflated.
