### ISSUE TITLE
Error when uploading data with missing cols

### ISSUE THREAD

**Issue by ignatiusm** [dragonfly-science/fish-ibi-calculator#63]
![image](https://user-images.githubusercontent.com/11403879/203652152-00775e44-04f7-4e63-a247-e3df422ec8cc.png)
 
when uploading 
[test-data.csv](https://github.com/dragonfly-science/fish-ibi-calculator/files/10079344/test-data.csv) *note: this file is not the same as the one with the same name below - sorry for crappy naming!*

**Comment by ignatiusm** [comment]
Ditto with other col names:
![image](https://user-images.githubusercontent.com/11403879/203653232-b2125eea-49b0-4697-a7b9-3cdcac1b6300.png)

**Comment by ignatiusm** [comment]
@yvanrichard it looks like uploading a custom csv is broken at the moment. 

I had to manually change col names to meet expected (see errors above), and then once this was sorted, I got a subsequent error:
 
![image](https://user-images.githubusercontent.com/11403879/203653703-4eb77174-9259-4940-b3bc-011aeeeb0f1f.png)

**Comment by ignatiusm** [comment]
Here is data from allnzIBI_NPS.xlsm input tab: 
[test-data.csv](https://github.com/dragonfly-science/fish-ibi-calculator/files/10079407/test-data.csv)

**Comment by yvanrichard** [comment]
Yes, the table was passed to the functions downstream.
I just added a requirement on the expected columns for the cleanTable function to run.
But now the issue table is empty... I'll fix it.

**Comment by yvanrichard** [comment]
Done
