### ISSUE TITLE
Blank page for error checking

### ISSUE THREAD

**Issue by ignatiusm** [dragonfly-science/fish-ibi-calculator#65]
when using this [empty-test-data.csv](https://github.com/dragonfly-science/fish-ibi-calculator/files/10099543/empty-test-data.csv) data file, after assigning the correct field names, the next page is empty:

![image](https://user-images.githubusercontent.com/11403879/204168315-0b9f5aa4-ee03-49c4-985f-5d9da3dfb24c.png)

here is the log: 

![image](https://user-images.githubusercontent.com/11403879/204168339-3e7f392e-84fa-4ff9-868f-2c29a8469703.png)

**Comment by ignatiusm** [comment]
Actually, this behaviour is shown even if one column name is manually set.

Here is an example with just one col mismatched: 
[empty-test-data.csv](https://github.com/dragonfly-science/fish-ibi-calculator/files/10099553/empty-test-data.csv)


All columns matching works as expected: 
[test-data.csv](https://github.com/dragonfly-science/fish-ibi-calculator/files/10099554/test-data.csv)

**Comment by yvanrichard** [comment]
The reactivity wasn't quite right when fields were manually renamed.
Should be fixed now.
@ignatiusm Can you please check and mark this as resolved if so?

**Comment by ignatiusm** [comment]
Nice! resolved
