### ISSUE TITLE
Map tool tip category label

### ISSUE THREAD

**Issue by ignatiusm** [dragonfly-science/fish-ibi-calculator#68]
![image](https://user-images.githubusercontent.com/11403879/206600910-f4db1a67-3929-4987-9a6e-38c043f10673.png)

Whoops, when reviewing I forgot to click on the dots! There is a label in the tooltip that says 'NPS category', when users have selected a region and are viewing regional results, it would be great if this label says 'Regional IBI category' (or maybe just 'IBI category'; as it isn't NationalPS).

Not urgent! would be cool if this could be done next week sometime :)

**Comment by yvanrichard** [comment]
That looks done
