### ISSUE TITLE
Unicode chars in uploaded csv (is there a way to handle these automagically?)

### ISSUE THREAD

**Issue by ignatiusm** [dragonfly-science/fish-ibi-calculator#70]
Character encoding is hard! User has reported the following, but there are likely to be similar issues with macrons etc:

_Funny things happen to ‘apostrophes‘ (e.g. Waikouaiti at Orbell’s Crossing -> Waikouaiti at Orbellâ€™s Crossing) when using CSV files._

@yvanrichard do you have any ideas how to handle this automatically - or should I go back and ask for an example file from user?

**Comment by yvanrichard** [comment]
Do we have an example file?

**Comment by yvanrichard** [comment]
I added an attempt to deal with the file encoding.
It might work but we need an example file of theirs to check.
It's bloody Excel on Windows converting apostrophes to smart quotes and then saving to Windows-1252 instead of UTF-8 I think.
