### ISSUE TITLE
Change graph title and y-axis to 'site visits' 

### ISSUE THREAD

**Issue by ignatiusm** [dragonfly-science/fish-ibi-calculator#71]
Currently the plot says it is a count of sites by score, but really it is 'stratum' (or unique site visits).

Can you please change title and y-axis to reflect this? I suggest the term 'site visit' but I am open to counter suggestions...

![image](https://user-images.githubusercontent.com/11403879/220203091-c04f7c13-52b6-437f-98f6-2e1705f69794.png)

**Comment by ignatiusm** [comment]
slightly updated wording above ^^

**Comment by yvanrichard** [comment]
Changed to "site visits"
