### ISSUE TITLE
Change graph and map colour palette to match colours from NPS-FM E.coli / LAWA colours

### ISSUE THREAD

**Issue by ignatiusm** [dragonfly-science/fish-ibi-calculator#72]
Looking at colours from [LAWA](https://www.lawa.org.nz/explore-data/river-quality/#/tb-national):

IBI has 5 categories (A-D + no species)

E.coli in lawa has 6 (A-E + not assessed)

Clarity has 5 (A-D + not assessed)

MFE have requested that we match the ecoli colours, but given that 'no species' can have a few different interpretations (not all bad) I think we should follow the Clarity colours.

Codes given below:

score | code
-------- | -------
A  | #20A7AD
B |  #85BB5B
C | #FFC316
D | #74C0C1
No species | #74C0C1

Yay for ColorZilla add-on for firefox :)  

![image](https://user-images.githubusercontent.com/11403879/220465805-69901faf-6af7-4002-a589-0b85da41ee7f.png)

**Comment by yvanrichard** [comment]
Actually, [Absolute Enable Right Click & Copy](https://addons.mozilla.org/en-US/firefox/addon/absolute-enable-right-click/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser) for the win. It enables right-clicking, "Inspect" and therefore getting the actual CSS colour.
